# 日志文件路径
log:
  file:
    path: logs/${spring.application.name}/${spring.profiles.active}
logging:
  file: ${log.file.path}/${spring.application.name}-info.log
  level:
    com: info
spring:
  application:
    name: SalaryCalculator
  profiles:
    active: dev     # 本地环境
#    active: dev       # 本地环境
#    active: test      # 开发测试环境
#    active: pre       # 预发环境
#    active: online    # 生产环境

  # 驱动配置信息
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:oracle:thin:@192.168.0.202:1521:orcl
    username: SSDW
    password: ssdw2018
    driver-class-name: oracle.jdbc.driver.OracleDriver

  #连接池的配置信息
  ## 初始化大小，最小，最大
  druid:
    initialSize: 20
    minIdle: 20
    maxActive: 30
    ## 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

# mybatis_config
mybatis:
  mapper-locations: classpath*:mapper/*.xml
pythonScript-path: D:/PythonScript.py